version: '3'
services:
  web:
    image: nginx:latest
    container_name: 'app-web'
    ports:
      - "3000:80"
    volumes:
      - ./cfg/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app
    networks:
      - frontend
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    container_name: 'app-php'
    volumes:
      - ./src:/app
      - ./cfg/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - frontend
      - backend
  mysql:
    image: mariadb:latest
    container_name: 'app-db'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'app_user'
      MYSQL_DATABASE: 'app_db'
      MYSQL_PASSWORD: 'password'
    volumes:
      - app-db-data:/var/lib/mysql
    networks:
      - backend
  

volumes:
  app-db-data:

networks:
  frontend:
    name: app-frontend
  backend:
    name: app-backend
